spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kyle_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ilyana
    password: ilyana
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update