---
openapi: 3.0.3
info:
  title: Kyle management API
  description: Internal API
  contact:
    name: Eddy Amegandji
    email: eddysamegandji@gmail.com
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: local development
tags:
  - name: "customer-resource"
paths:
  /customers:
    get:
      summary: "Retrieve all the customers"
      tags: ["customer-resource"]
      operationId: getCustomers
      security:
        - basicAuth: []
      responses:
        '200':
          description: "List retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerApi'

    post:
      summary: "Create a new customer"
      tags: ["customer-resource"]
      operationId: createCustomer
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerApi'
      responses:
        '200':
          description: "A detailed customer"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerApi'

components:
  responses:
    '401':
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    '403':
      description: "Forbidden"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
  schemas:
    ApiError:
      type: object
      properties:
        status:
          type: integer
        error:
          type: string
        path:
          type: string
        timestamp:
          type: number
          format: double
        message:
          type: string

    UserApi:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        fullName:
          type: string
        email:
          type: string
        phone:
          type: string
        firstConnectionDate:
          type: string
          format: date-time
        lastConnectionDate:
          type: string
          format: date-time
        creationDate:
          type: string
          format: date-time
        creationUserId:
          type: integer
        deleteDate:
          type: string
          format: date-time
        deleteUserId:
          type: integer
        active:
          type: boolean
          default: true
#        skills:
#          type: object
#          properties:
#            id:
#              type: integer

    CustomerApi:
      type: object
      properties:
        customerId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        fullName:
          type: string
        birthDate:
          type: string
          format: date-time
        birthCity:
          type: string
        birthDepartment:
          type: string
        address1:
          type: string
        address2:
          type: string
        zipCode:
          type: string
        city:
          type: string
        country:
          type: string
        mobilePhone:
          type: string
        emailAddress:
          type: string
        companyName:
          type: string
        companyPosition:
          type: string
        workPhone:
          type: string

